# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[4.11,)" # Require at least 4.11.x
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"

authors = "${mod_authors}"
description = """
With some practical enchantment added, this mod is inspired by more enchantment, in which the code is completely rewritten.
添加了一些实用的附魔, 此模组灵感来源于更多附魔, 其中代码完全重写
"""
[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"